config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  resources :recipes do
    resources :reviews, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  mount_uploader :recipe_img, ImageUploader
  has_many :reviews, dependent: :destroy
  def avg_score
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f
    else
      0.0
    end
  end
  def review_score_percentage
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f*100/5
    else
      0.0
    end
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
  validates :score, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews, dependent: :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  def after_sign_in_path_for(resource)
    recipes_path
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!,only: [:show]
  
  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    recipe = Recipe.create!(recipe_params)
    redirect_to recipes_path
  end

  def show
    @recipe = Recipe.find(params[:id])
    @review = Review.new
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    recipe = Recipe.find(params[:id])
    recipe.update(recipe_params)
    redirect_to recipes_path
  end

  def recipe_params
    params.require(:recipe).permit(:name,:maker,:recipe_img)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!,only: [:create]

  def index
    @recipe = Recipe.find(params[:recipe_id])
    @reviews = @recipe.reviews
  end
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    if @review.save
      redirect_to recipe_reviews_path(@review.recipe)
    else
      @recipe = Recipe.find(params[:recipe_id])
      render "recipes/show"
    end
  end
  private
  def review_params
    params.require(:review).permit(:recipe_id, :score, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/homes/top.html.erb
<section class="section mt-6">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-10">
        <p class="is-size-2 has-text-weight-bold has-text-centered pt-6 pb-6">
          美味しいレシピを探そう
        </p>
        <div class="columns is-centered mt-6">
          <div class="column is-3">
            <%= link_to "ログイン", new_user_session_path,class: "button is-fullwidth" %>
            <%= link_to "新規登録", new_user_registration_path,class: "button is-fullwidth mt-4" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeReview</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://kit.fontawesome.com/484e6509e8.js" crossorigin="anonymous"></script>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <strong class="is-size-3" style="font-family: Gill Sans, sans-serif;">recipe_review</strong>
        <% end %>
        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <%= link_to recipes_path, class: "navbar-item" do %>
            レシピ一覧
          <% end %>
          <%= link_to new_recipe_path, class: "navbar-item" do %>
            レシピを新規投稿する
          <% end %>
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
            <% if user_signed_in? %>
              <p class="navbar-item">ようこそ <%= current_user.username %> さん</p>
            <% end %>
            <div class="buttons">
              <% if user_signed_in? %>
                <%= link_to destroy_user_session_path, method: :delete, class: "button" do %>
                  ログアウト
                <% end %>
              <% else %>
                <%= link_to new_user_session_path, class: "button" do %>
                  ログイン
                <% end %>
                <%= link_to new_user_registration_path, class: "button" do %>
                  新規登録
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

  <script type="text/javascript">
    document.querySelector('.navbar-burger').addEventListener("click", toggleNav);

    function toggleNav() {
            var nav = document.querySelector('.navbar-menu');
            if(nav.className == "navbar-menu") {
                nav.className = "navbar-menu is-active";
            } else {
                nav.className = "navbar-menu";
            }
    }
  </script>

app/views/recipes/edit.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-4">
        <p class="is-size-4 mb-3" style="color: white">レシピを編集する </p>
        <%= form_with model: @recipe, local: true do |f| %>
          <div class="field">
            <%= f.label :name, "レシピ名" %>
            <%= f.text_field :name, class: "input" %>
          </div>
          <div class="field">
            <%= f.label :maker, "レシピ元" %>
            <%= f.text_field :maker, class: "input" %>
          </div>
          <div class="field">
            <%= f.label :recipe_img, "レシピ画像" %>
            <%= f.file_field :recipe_img %>
          </div>
          <div class="actions">
            <%= f.submit "投稿する", class: "button mt-3 is-success"  %>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/recipes/index.html.erb
<section class="section mt-6">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <% @recipes.each do |recipe| %>
          <div class="card mb-6">
            <header class="card-header">
              <p class="card-header-title">
                <%= link_to recipe.name, edit_recipe_path(recipe),class:"recipename" %>
              </p>
            </header>
            <div class="card-content">
              <div class="content">
                <p>レシピ元：<%= recipe.maker %></p>
              </div>
              <div class="content">
                <% if recipe.recipe_img? %>
                  <p><%= image_tag recipe.recipe_img.url %></p>
                <% end %>
              </div>
              <div class="content average-score">
                <div class="star-rating mb-2">
                  <div class="star-rating-front" style="width: <%= recipe.review_score_percentage %>%">
                    ★★★★★
                  </div>
                  <div class="star-rating-back">
                    ★★★★★
                  </div>
                </div>
                <div class="average-score-display ml-3 pt-2">
                  <%= recipe.avg_score %>点(<%= recipe.reviews.count %>件のレビュー)
                </div>
              </div>
            </div>
            <div class="card-footer">
              <%= link_to recipe_reviews_path(recipe), class: "button card-footer-item" do %>
                レビューを見る
              <% end %>
              <%= link_to recipe_path(recipe), class: "button card-footer-item" do %>
                レビューを書く
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/recipes/new.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-4">
        <p class="is-size-4 mb-3" style="color: white">レシピを新しく投稿する </p>
        <%= form_with model: @recipe, local: true do |f| %>
          <div class="field">
            <%= f.label :name, "レシピ名" %>
            <%= f.text_field :name, class: "input" %>
          </div>
          <div class="field">
            <%= f.label :maker, "レシピ元" %>
            <%= f.text_field :maker, class: "input" %>
          </div>
          <div class="field">
            <%= f.label :recipe_img, "レシピ画像" %>
            <%= f.file_field :recipe_img %>
          </div>
          <div class="actions">
            <%= f.submit "投稿する", class: "button mt-3 is-success"  %>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/recipes/show.html.erb
<section class="section mt-6">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <div class="card mb-6">
          <header class="card-header">
            <p class="card-header-title">
              <%= @recipe.name %>
            </p>
          </header>
          <div class="card-content">
            <div class="content">
              <%= @recipe.maker %>
            </div>
            <div class="content average-score">
              <div class="star-rating mb-2">
                <div class="star-rating-front" style="width: <%= @recipe.review_score_percentage %>%">★★★★★</div>
                <div class="star-rating-back">★★★★★</div>
              </div>
              <div class="average-score-display ml-3 pt-2">
                <%= @recipe.avg_score %>点（<%= @recipe.reviews.count %>件のレビュー）
              </div>
            </div>
          </div>
        </div>
        <%= render 'reviews/form', review: @review, recipe:@recipe %>
      </div>
    </div>
  </div>
</section>

app/views/reviews/_form.html.erb
<p class="is-size-4 mb-3" style="color: white">レビューを書く </p>

<% if review.errors.any? %>
  <div class="notification is-danger">
    <h2>エラーがあります。</h2>
    <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="rating-box mt-3">
  <%= form_with model: review, url: recipe_reviews_path(recipe), local:true do |f| %>
    <div class="main-rating">
      <div class="ratings mb-3"style="color: yellow">
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
      </div>
      <div class="ml-3 rating-value-display" style="color: white" >
        <span id="rating-value-display"></span>/5
      </div>
    </div>
    <%= f.hidden_field :recipe_id, value: recipe.id %>
    <%= f.hidden_field :score, id: "rating-value" %>
    <%= f.text_field :content, class: "textarea" %>
    <%= f.submit "保存", class: "button mt-3" %>
    <%= link_to "他のレビュー", recipe_reviews_path(recipe), class:"button light ml-3 mt-3" %>
  <% end %>
</div>

<%= javascript_include_tag "reviews.js" %>

app/views/reviews/index.html.erb
<section class="section mt-6">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <div class="card mb-6">
          <header class="card-header">
            <p class="card-header-title">
              <%= @recipe.name %>
            </p>
          </header>
          <div class="card-content">
            <div class="cotent">
              <%= @recipe.maker %>
            </div>
            <div class="content average-score">
              <div class="star-rating mb-2">
                <div class="star-rating-front" style="width: <%= @recipe.review_score_percentage %>%">★★★★★</div>
                <div class="star-rating-back">★★★★★</div>
              </div>
              <div class="average-score-display ml-3 pt-2">
                <%= @recipe.avg_score %>点（<%= @recipe.reviews.count %>件のレビュー）
              </div>
            </div>
          </div>
        </div>
        <table class="table is-fullwidth has-text-centered">
          <thead>
            <tr>
              <th>ユーザー</th><th>点数</th><th>内容</th>
            </tr>
          </thead>
          <tbody>
            <% @reviews.each do |review| %>
              <tr>
                <td><%= review.user.username %></td>
                <td><%= review.score %></td>
                <td><%= review.content %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>